site_name: DevOps Docs
site_url: https://skucukalioglu.github.io/public-pages/
nav:
  - Home:
      'About': index.md
  - DevOps Guides:
      'Test': devops-guides/README.md
  - Troubleshooting Guides:
      'Edge Servers': troubleshooting-guides/README.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
markdown_extensions:
  - attr_list