site_name: Public Pages
site_url: https://skucukalioglu.github.io/public-pages/
nav:
  - Home:
      'About': index.md
  - DevOps Guides:
      'Main': devops-guides/README.md
  - Troubleshooting Guides:
      'Troubleshooting': troubleshooting-guides/README.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
markdown_extensions:
  - attr_list